### ISSUE TITLE
add compatibility for more themes

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/full-width-page-templates#4]
- OceanWP
- Astra
- Divi
- ++ make sure top 50 free wp themes works

1. Install the theme
2. Install the obfx companion
3. try to import a template
4. If the new page doesn't look good due to the page template issue, follow this guide to submit a fix : https://github.com/Codeinwp/full-width-page-templates#how-to-make-a-theme-compatible-with-the-full-width-template

Note: This is a good first issue

cc @abaicus @rodica-andronache

**Comment by abaicus** [comment]
@stefan-cotitosu Do you think you could take on this? 👍 :D

**Comment by stefan-cotitosu** [comment]
@abaicus Yes, I will try.
