### ISSUE TITLE
Add Neve notice

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/full-width-page-templates#9]
Let's add a timed notice in the plugin that recommends Neve:

- the notice appears after the plugin is activated and it is dismissable
- notice text:
>Do you enjoy working with Elementor?
>Check out Neve, our new FREE multipurpose theme. It's simple, fast and fully compatible with both Elementor and Gutenberg. See [theme demo](https://themeisle.com/demo/?theme=Neve ).

- the link will be to our site https://themeisle.com/demo/?theme=Neve (open in new tab)

**Comment by cosmin-serbanescu** [comment]
@sab2ina , cannot add the Neve notice here as this is a composer library, not a WP plugin
